version: '3.8'

#setting up network configuration for the redis cluster
networks: 
  redis-cluster-network: 
    driver: bridge #default network driver for docker networking, this will create a private internal network within the docker network different from the host.
    ipam: 
      config: 
        - subnet: 172.20.0.0/16

services:
  redis-node-1:
    image: redis:8.8.0
    container_name: token-store-master-1
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      redis-cluster-network:
        ipv4_address: 172.20.0.11
    ports:
      - "7001:6379"

  redis-node-2:
    image: redis:8.8.0
    container_name: token-store-master-2
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      redis-cluster-network:
        ipv4_address: 172.20.0.12
    ports:
      - "7002:6379"

  redis-node-3:
    image: redis:8.8.0
    container_name: token-store-master-3
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      redis-cluster-network:
        ipv4_address: 172.20.0.13
    ports:
      - "7003:6379"

  redis-node-4:
    image: redis:8.8.0
    container_name: token-store-replica-1
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      redis-cluster-network:
        ipv4_address: 172.20.0.14
    ports:
      - "7004:6379"

  redis-node-5:
    image: redis:8.8.0
    container_name: token-store-replica-2
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      redis-cluster-network:
        ipv4_address: 172.20.0.15
    ports:
      - "7005:6379"

  redis-node-6:
    image: redis:8.8.0
    container_name: token-store-replica-3
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      redis-cluster-network:
        ipv4_address: 172.20.0.16
    ports:
      - "7006:6379"


  # cluster initializer — runs once to join nodes into a cluster
  redis-cluster-init: 
    image: redis:8.8.0
    container_name: token-cluster-init
    depends_on: 
      - redis-node-1
      - redis-node-2
      - redis-node-3
      - redis-node-4
      - redis-node-5
      - redis-node-6
    networks:
      - redis-cluster-network
      # --cluster-replicas 1 means 1 replica per primary (3 primaries + 3 replicas)
    command: > 
      bash -c "sleep 5 && redis-cli --cluster create
      172.20.0.11:6379
      172.20.0.12:6379
      172.20.0.13:6379
      172.20.0.14:6379
      172.20.0.15:6379
      172.20.0.16:6379
      --cluster-replicas 1 --cluster-yes"
    restart: on-failure