package com.triluong.ratelimiter.model;


import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.Data;

/**
 *
 * Represent the data model for a request that is received by the rate-limiter
 * This model will be stored in a Nosql database, specifically the DynamoDb
 *
 * **/
@DynamoDBTable(tableName="RequestInfo")
public class Request {
    private String id;
    private String msrp;
    private String cost;

    //Setting getters for the dynamodb attributes
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getId(){
        return id;
    }

    @DynamoDBAttribute
    public String getMsrp() {
        return msrp;
    }

    @DynamoDBAttribute
    public String getCost() {
        return cost;
    }
}
