cc_binary(
    name = "redis-cache", 
    srcs = ["redis/redis_main.cc"]
    deps = [
        "@boost"
    ]
)

cc_binary(
    name = "aegis-engine-main",
    srcs = ["aegis_engine_main.cc"],
    deps = [
        "@boost.program_options",
    ],
)