###############################################################################
# Bazel now uses Bzlmod by default to manage external dependencies.
# Please consider migrating your external dependencies from WORKSPACE to MODULE.bazel.
#
# For more details, please check https://github.com/bazelbuild/bazel/issues/18958
###############################################################################
module(
    name = "aegis-engine-main",
)

bazel_dep(name = "boost.program_options", version = "1.89.0.bcr.1")
bazel_dep(name = "boost.filesystem", version = "1.89.0.bcr.1")
bazel_dep(name = "boost.system", version = "1.89.0.bcr.1")
bazel_dep(name = "boost.algorithm", version = "1.89.0.bcr.1")
bazel_dep(name = "boost.asio", version = "1.89.0.bcr.1")
bazel_dep(name = "boost.thread", version = "1.89.0.bcr.1")
bazel_dep(name = "googletest", version = "1.14.0")
bazel_dep(name = "rules_cc", version = "0.0.9")
bazel_dep(name = "rules_proto",     version = "6.0.0")   # proto_library rule
bazel_dep(name = "rules_proto_grpc_cpp", version = "0.0.1")  # cpp_grpc_library rule
bazel_dep(name = "grpc",            version = "1.62.0")
bazel_dep(name = "protobuf",        version = "26.0")


local_path_override(
    module_name = "redis_plus_plus",
    path = "third_party/redis_plus_plus",
)
